### ISSUE TITLE
Semantic Search Product won't Build

### ISSUE THREAD

**Issue by narner** [ashvardanian/SwiftSemanticSearch#11]
After following instructions in the readme; getting these errors when trying to build the SwiftSemanticSearch project:

![CleanShot 2024-12-05 at 13 45 04](https://github.com/user-attachments/assets/7baf7f7d-e5dd-4095-845b-88fa842cd8e2)

**Comment by ashvardanian** [comment]
@narner, Seems like an Xcode issue. Try updating the dependencies on project page.
