### ISSUE TITLE
Building the app on iPhone 15 pro immediately results in disk error

### ISSUE THREAD

**Issue by warronbebster** [ashvardanian/SwiftSemanticSearch#4]
Running on a simulator works fine. Running on an actual device results in an immediate permissions error:

![image](https://github.com/user-attachments/assets/41b2f30c-a6b1-41a6-8524-82ad4608542f)

**Comment by ashvardanian** [comment]
Interesting. I'm not sure its something I can debug remotely, but a good solution may be to change the directory, where the data is saved.

**Comment by Hyukjae-Jang** [comment]
The same issue with iPhone 16 Plus, iOS 18.0

**Comment by ashvardanian** [comment]
@Hyukjae-Jang, any chance you have a patch in mind?

**Comment by Hyukjae-Jang** [comment]
Sorry. I'm pretty much new to iOS development.
