### ISSUE TITLE
Property 'id' requires that 'Self' be a class type

### ISSUE THREAD

**Issue by dmitrilosev** [ashvardanian/SwiftSemanticSearch#5]
Running the project causes an error in the Swallow library

<img width="1207" alt="Screenshot 2024-08-13 at 2 46 04 PM" src="https://github.com/user-attachments/assets/61fdff2d-58f1-43a0-83ad-a1b4a5fd853c">

**Comment by ashvardanian** [comment]
That's coming from @vmanot's library, I believe.

**Comment by vmanot** [comment]
@dmitrilosev which version of Xcode are you on?

**Comment by hfnvbh** [comment]
Hi, having same problem at xcode 16.0

**Comment by Hyukjae-Jang** [comment]
Me, too. My xcode is 16.1
